name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 ## faz o git checkout para a maquina ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - run: go test
      - run: go run sum.go
